### PR TITLE
Support reading from and writing to memory

### PR DESCRIPTION
**Pull request by chfw**
Hi,

ezodf lacks of such support while odfpy had it. I originally aimed at "ods" file type only but it turns out "odt", "odg" and "odp" are OK with my patches too.

The patches only modifies the behavior of file opening and file save. Although it causes back compatibility concerns because opendoc was inserted a file_content parameter, I don't think opening from a memory stream ever worked. Hence, it is pretty safe to add such an extra paramter. Test cases were appended. 

I am looking forward to its release in pypi as my library pyexcel-ods3 would like to have this support. 

Cheers

chfw

### CODE REVIEW

**Comment by michael-k** [comment]
@T0ha: any plans on merging this?

**Comment by T0ha** [comment]
Thanks. Sorry was a bit busy.

**Comment by T0ha** [comment]
I'll include it in next package

**Comment by chfw** [comment]
Excellent news. I am looking forward to the new release.

**Comment by T0ha** [comment]
May be I'm wrong, but what's `file_content` for? Are you going to open file and ByteStream at once?
Seems it's better to check if filename instance of StringIO or string.

**Comment by chfw** [comment]
I am sorry for the late response. I got some time today to revisit why I added file_content. 

Originally, file_content was intended to be place holder for the content in memory. Because my content came in as <str>, and I have not wrapped it with StringIO, hence opendoc confuses it with filename and  initializes fm as FileManager instead of BytesStreamManager. For that reason, I added 'file_content'. 

Your subsequent commit to remove 'file_content' is nicer solution. I am looking forward to the pypi release.

**Comment by T0ha** [comment]
Thanks, all. I'm happy it works for you. If we accept it works I'll pack next minor release.

**Pull request merged**
